### ISSUE TITLE
After some time of running

### ISSUE THREAD

**Issue by ghost** [storj-archived/kfs#30]
```
/home/marek/.nvm/versions/node/v4.5.0/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kfs/lib/s-bucket.js:225
        callback(null);
        ^

TypeError: callback is not a function
    at /home/marek/.nvm/versions/node/v4.5.0/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kfs/lib/s-bucket.js:225:9
```

**Comment by ghost** [comment]
```
{"level":"info","message":"data channel connection opened","timestamp":"2016-10-15T12:58:48.878Z"}
{"level":"warn","message":"calculated hash does not match the expected result","timestamp":"2016-10-15T12:58:50.637Z"}
/home/storj/.nvm/versions/node/v4.5.0/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kfs/lib/s-bucket.js:225
        callback(null);
        ^

TypeError: callback is not a function
    at /home/storj/.nvm/versions/node/v4.5.0/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kfs/lib/s-bucket.js:225:9
```

again

**Comment by 161chihuahuas** [comment]
New storj-lib released moments ago.
