### ISSUE TITLE
Using KFS@3.0.0 result with Syntax error: Unexpected token

### ISSUE THREAD

**Issue by coolfarmer** [storj-archived/kfs#45]
I have a corrupted database so I want to use the compact tool in KFS package.

Package correctly installed:

```
C:\WINDOWS\system32>npm install -g kfs@3.0.0
|
> leveldown@1.6.0 install C:\Users\mediacenter\AppData\Roaming\npm\node_modules\kfs\node_modules\leveldown
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.1.0
prebuild-install info looking for local prebuild @ prebuilds\leveldown-v1.6.0-node-v46-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\mediacenter\AppData\Roaming\npm-cache\_prebuilds\https-github.com-level-leveldown-releases-download-v1.6.0-leveldown-v1.6.0-node-v46-win32-x64.tar.gz
prebuild-install http request GET https://github.com/level/leveldown/releases/download/v1.6.0/leveldown-v1.6.0-node-v46-win32-x64.tar.gz
prebuild-install http 200 https://github.com/level/leveldown/releases/download/v1.6.0/leveldown-v1.6.0-node-v46-win32-x64.tar.gz
prebuild-install info downloading to @ C:\Users\mediacenter\AppData\Roaming\npm-cache\_prebuilds\https-github.com-level-leveldown-releases-download-v1.6.0-leveldown-v1.6.0-node-v46-win32-x64.tar.gz.8576-92938a5b.tmp
prebuild-install info renaming to @ C:\Users\mediacenter\AppData\Roaming\npm-cache\_prebuilds\https-github.com-level-leveldown-releases-download-v1.6.0-leveldown-v1.6.0-node-v46-win32-x64.tar.gz
prebuild-install info unpacking @ C:\Users\mediacenter\AppData\Roaming\npm-cache\_prebuilds\https-github.com-level-leveldown-releases-download-v1.6.0-leveldown-v1.6.0-node-v46-win32-x64.tar.gz
prebuild-install info unpack resolved to C:\Users\mediacenter\AppData\Roaming\npm\node_modules\kfs\node_modules\leveldown\build\Release\leveldown.node
prebuild-install info unpack required C:\Users\mediacenter\AppData\Roaming\npm\node_modules\kfs\node_modules\leveldown\build\Release\leveldown.node successfully
prebuild-install info install Prebuild successfully installed!
C:\Users\mediacenter\AppData\Roaming\npm\kfs -> C:\Users\mediacenter\AppData\Roaming\npm\node_modules\kfs\bin\kfs.js
kfs@3.0.0 C:\Users\mediacenter\AppData\Roaming\npm\node_modules\kfs
├── merge@1.2.0
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── readable-stream@2.2.2 (buffer-shims@1.0.0, inherits@2.0.3, string_decoder@0.10.31, util-deprecate@1.0.2, process-nextick-args@1.0.7, core-util-is@1.0.2, isarray@1.0.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── leveldown@1.6.0 (bindings@1.2.1, fast-future@1.0.2, nan@2.5.1, abstract-leveldown@2.6.1, prebuild-install@2.1.0)
└── async@2.1.4 (lodash@4.17.4)
```

But when I want to run the command, I have always this error :

```
E:\>kfs -d E:\\godzilla_gui\\storjshare-349319 compact
C:\Users\mediacenter\AppData\Roaming\npm\node_modules\kfs\bin\kfs.js:9
const {homedir} = require('os');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
```

**Comment by 161chihuahuas** [comment]
You need to be running Node.js LTS (6.9.x)

**Comment by coolfarmer** [comment]
I just installed version 6.9.5 (with NPM 3.10.10)
I have reinstalled KFS 3.0.0.

And got that new error
```
C:\Windows\System32>kfs -d E:\\godzilla_gui\\storjshare-349319 compact
C:\Users\mediacenter\AppData\Roaming\npm\node_modules\kfs\node_modules\bindings\bindings.js:83
        throw e
        ^

Error: Module version mismatch. Expected 48, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at bindings (C:\Users\mediacenter\AppData\Roaming\npm\node_modules\kfs\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (C:\Users\mediacenter\AppData\Roaming\npm\node_modules\kfs\node_modules\leveldown\leveldown.js:4:46)
    at Module._compile (module.js:570:32)
```

Any idea? :/

**Comment by 161chihuahuas** [comment]
You need to rebuild the native modules. Quickest way is to:

```
npm remove -g kfs && npm install -g kfs
```
