### ISSUE TITLE
Another Error with google-drive-ocamlfuse when running Storj_Farmer_Contracts.js

### ISSUE THREAD

**Issue by ne0ark** [storj-archived/kfs#52]
storjshare -V

  * daemon: 2.5.0, core: 6.3.0, protocol: 1.1.0

----------------------------------

node Storj_Farmer_Contracts.js 

assert.js:85
  throw new assert.AssertionError({
  ^
AssertionError: Table path is not a valid KFS instance
    at Btable._validateTablePath (/root/bin/node_modules/kfs/lib/b-table.js:97:7)
    at Btable._open (/root/bin/node_modules/kfs/lib/b-table.js:62:12)
    at new Btable (/root/bin/node_modules/kfs/lib/b-table.js:51:10)
    at module.exports (/root/bin/node_modules/kfs/index.js:15:34)
    at new EmbeddedStorageAdapter (/root/bin/node_modules/storj-lib/lib/storage/adapters/embedded.js:30:14)
    at Object.<anonymous> (/root/bin/Storj_Farmer_Contracts.js:83:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

------------------------------------

**Comment by 161chihuahuas** [comment]
This is expected, you did not provide a valid path to a KFS directory

**Comment by ne0ark** [comment]
I am also getting this error when starting with a conf file:

tail -20 e1ac09725fbf507c3813caf6c8fd6a64b87eba47.log

assert.js:85
  throw new assert.AssertionError({
  ^
AssertionError: Table path is not a valid KFS instance
    at Btable._validateTablePath (/usr/lib/node_modules/storjshare-daemon/node_modules/kfs/lib/b-table.js:97:7)
    at Btable._open (/usr/lib/node_modules/storjshare-daemon/node_modules/kfs/lib/b-table.js:62:12)
    at new Btable (/usr/lib/node_modules/storjshare-daemon/node_modules/kfs/lib/b-table.js:51:10)
    at module.exports (/usr/lib/node_modules/storjshare-daemon/node_modules/kfs/index.js:15:34)
    at new EmbeddedStorageAdapter (/usr/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/storage/adapters/embedded.js:30:14)
    at Object.<anonymous> (/usr/lib/node_modules/storjshare-daemon/script/farmer.js:24:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
root@narayan:~/.config/storjshare/logs# tail -50 e1ac09725fbf507c3813caf6c8fd6a64b87eba47.log
    at Object.<anonymous> (/usr/lib/node_modules/storjshare-daemon/script/farmer.js:24:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

assert.js:85
  throw new assert.AssertionError({
  ^
AssertionError: Table path is not a valid KFS instance
    at Btable._validateTablePath (/usr/lib/node_modules/storjshare-daemon/node_modules/kfs/lib/b-table.js:97:7)
    at Btable._open (/usr/lib/node_modules/storjshare-daemon/node_modules/kfs/lib/b-table.js:62:12)
    at new Btable (/usr/lib/node_modules/storjshare-daemon/node_modules/kfs/lib/b-table.js:51:10)
    at module.exports (/usr/lib/node_modules/storjshare-daemon/node_modules/kfs/index.js:15:34)
    at new EmbeddedStorageAdapter (/usr/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/storage/adapters/embedded.js:30:14)
    at Object.<anonymous> (/usr/lib/node_modules/storjshare-daemon/script/farmer.js:24:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
